
name: arcane_prospector

filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - ${LOG_PATH}app_*.log
  ignore_older: 6h  # Ignores 

  # From https://www.elastic.co/guide/en/ecs-logging/nodejs/current/pino.html
  parsers:
    - ndjson:
      overwrite_keys: true
      add_error_key: true
      expand_keys: true

processors:
  - timestamp:
      field: "${LOGGER_TIMESTAMP_KEY}"
      target_field: "@timestamp"
      timezone: UTC
      layouts:
        - '2006-01-02T15:04:05.999Z'
      test:
        - '2023-11-05T19:47:55.194Z'
  - drop_fields:
      fields: ["${LOGGER_TIMESTAMP_KEY}"]
  - rename:
      fields:
        - from: "${LOGGER_NESTED_KEY}.error"
          to: "error"
      ignore_missing: true
      fail_on_error: false
  - rename:
      fields:
        - from: "${LOGGER_NESTED_KEY}.${LOGGER_TESTNAME_KEY}"
          to: "testName"
      ignore_missing: true
      fail_on_error: false



output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}"]
  # Dynamically set the index name based on the environment field
  index: "arcane_prospector-%{[node_env]}-logs-%{+yyyy.MM.dd}"
  username: "elastic"
  password: ${ELASTICSEARCH_PASSWORD}

setup.template.enabled: false # Don't use Filebeat default or make my own; it's already made in ES

logging.level: debug

